In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
upload=files.upload()

Saving Dataset.csv to Dataset.csv

In [ ]:
dataset=pd.read_csv("Dataset.csv")

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          1439 non-null   object
 1   Date         1439 non-null   object
 2   CodedDay     1439 non-null   int64
 3   Zone         1439 non-null   int64
 4   Weather      1439 non-null   int64
 5   Temperature  1439 non-null   int64
 6   Traffic      1439 non-null   int64
dtypes: int64(5), object(2)
memory usage: 78.8+ KB

In [ ]:
dataset.head()

         Day      Date  CodedDay  Zone  Weather  Temperature  Traffic
0  Wednesday  01-06-18         3     2       35           17        2
1  Wednesday  01-06-18         3     3       36           16        3
2  Wednesday  01-06-18         3     4       27           25        5
3  Wednesday  01-06-18         3     5       23           23        3
4  Wednesday  01-06-18         3     6       18           42        2

In [ ]:
"""from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


dataset['Date'] = le.fit_transform(dataset['Date'])"""

"from sklearn.preprocessing import LabelEncoder\nle = LabelEncoder()\n\n\ndataset['Date'] = le.fit_transform(dataset['Date'])"

In [ ]:
dataset['Date'] = pd.to_datetime(dataset['Date'])

dataset['DayOfMonth'] = dataset['Date'].dt.day
dataset['Month'] = dataset['Date'].dt.month
dataset['Year'] = dataset['Date'].dt.year
dataset['DayOfWeek'] = dataset['Date'].dt.dayofweek

/tmp/ipykernel_7503/3358977384.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dataset['Date'] = pd.to_datetime(dataset['Date'])

In [ ]:
dataset.tail(10)

,Day,Date,CodedDay,Zone,Weather,Temperature,Traffic,DayOfMonth,Month,Year,DayOfWeek
1429,Friday,2018-10-06,5,135,18,25,4,6,10,2018,5
1430,Friday,2018-10-06,5,136,31,8,2,6,10,2018,5
1431,Friday,2018-10-06,5,137,13,11,4,6,10,2018,5
1432,Friday,2018-10-06,5,138,34,15,1,6,10,2018,5
1433,Friday,2018-10-06,5,139,5,43,4,6,10,2018,5
1434,Friday,2018-10-06,5,140,47,38,1,6,10,2018,5
1435,Friday,2018-10-06,5,141,15,8,4,6,10,2018,5
1436,Friday,2018-10-06,5,142,26,38,1,6,10,2018,5
1437,Friday,2018-10-06,5,143,16,34,3,6,10,2018,5
1438,Friday,2018-10-06,5,144,16,17,1,6,10,2018,5

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          1439 non-null   object
 1   Date         1439 non-null   datetime64[ns]
 2   CodedDay     1439 non-null   int64
 3   Zone         1439 non-null   int64
 4   Weather      1439 non-null   int64
 5   Temperature  1439 non-null   int64
 6   Traffic      1439 non-null   int64
 7   DayOfMonth   1439 non-null   int32
 8   Month        1439 non-null   int32
 9   Year         1439 non-null   int32
 10  DayOfWeek    1439 non-null   int32
dtypes: datetime64[ns](1), int32(4), int64(5), object(1)
memory usage: 101.3+ KB

In [ ]:
"""X = dataset.iloc[:, 2:6].values
y = dataset.iloc[:, 6:7].values"""

'X = dataset.iloc[:, 2:6].values\ny = dataset.iloc[:, 6:7].values'

In [ ]:
X = dataset[['CodedDay', 'Zone', 'Weather', 'Temperature',
             'DayOfMonth', 'Month', 'Year', 'DayOfWeek']].values

y = dataset['Traffic'].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=300, random_state=0)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300, random_state=0)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", round(accuracy_score(y_test, y_pred)*100, 2), "%")

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 17.71 %

Classification Report:

              precision    recall  f1-score   support

           1       0.16      0.19      0.17        54
           2       0.24      0.23      0.23        65
           3       0.13      0.13      0.13        52
           4       0.14      0.13      0.13        54
           5       0.21      0.19      0.20        63

    accuracy                           0.18       288
   macro avg       0.17      0.17      0.17       288
weighted avg       0.18      0.18      0.18       288

In [ ]:
import pickle

pickle.dump(model, open('model.pkl', 'wb'))
pickle.dump(sc_X, open('scaler.pkl', 'wb'))